### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by promontis** [nanderto/Akka.Net.Persistence.ServiceFabric#1]
Hi @nanderto!

Just wanted to say Hi and thanks for creating this code... it is awesome!!! If I'm not mistaken you previously had a fork of the Akka repo with a branch where you was implementing this stuff, and this is now the new repo, right?

Anyhow, do you need help on this? What are the open issues you currently face?

**Comment by nanderto** [comment]
@promontis ,
Thanks for the kind words, I asked the Akka.Net community for some feedback on their Gitter channel and they suggested separating it into its own repository. It was not in the right place before, but I did not know that until I figured out a couple of things, so yes it was previously in a branch on my fork of the Akka repro.
I don't have any open issues but I could use a code review. I am sure there are others that know Service Fabric and Akka better than me. I am also still trying to figure out how others have built unit tests for their persistence code so that I can emulate them. Help in either of these areas would be appreciated.

**Comment by alexvaluyskiy** [comment]
@nanderto it is peraty easy to add unit tests. Just add a nuget package to your test project - "Akka.Persistence.TestKit". And create ".cs" file like this
https://github.com/akkadotnet/Akka.Persistence.Redis/blob/dev/src/Akka.Persistence.Redis.Tests/RedisJournalSpec.cs

**Comment by alexvaluyskiy** [comment]
But it is much easier to debug your persistence project, where it is a part of Akka solution :)

**Comment by nanderto** [comment]
@alexvaluyskiy  Thanks for the clue on how to run the tests, I was completely lost on that. 

I have a couple of questions. Is the journal only ever supposed to do a soft delete, marking the record as deleted but never actually deleting it?
and I have this error message from one of my tests:

Test Name:  Akka.Persistence.ServiceFabric.Tests.ServiceFabricJournalSpec.Journal_should_not_replay_permanently_deleted_messages_on_range_deletion
Test FullName:  Akka.Persistence.ServiceFabric.Tests.ServiceFabricJournalSpec.Journal_should_not_replay_permanently_deleted_messages_on_range_deletion
Test Source:     : line 0
Test Outcome:   Failed
Test Duration:  0:00:01.067

Result StackTrace:  
at Akka.TestKit.Xunit2.XunitAssertions.AssertTrue(Boolean condition, String format, Object[] args)
   at Akka.TestKit.TestKitBase.AssertPredicateIsTrueForMessage[T](Predicate`1 isMessage, T m, String hint)
   at Akka.TestKit.TestKitBase.  c__DisplayClass91_0`1. ExpectMsg b__0(T m, IActorRef sender)
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog)
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`2 assert, String hint)
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Predicate`1 isMessage, Nullable`1 timeout, String hint)
   at Akka.Persistence.TestKit.Journal.JournalSpec.Journal_should_not_replay_permanently_deleted_messages_on_range_deletion()
Result Message: 
Got a message of the expected type  Akka.Persistence.ReplayedMessage . Also expected the predicate to return true but the message {ReplayedMessage message: Persistent pid: , seqNr: 4, deleted: False, manifest: p-1, sender: [akka://ServiceFabricJournalSpec/user/testActor1#293731468], payload: a-4, writerGuid:   } of type  Akka.Persistence.ReplayedMessage  did not match
Expected: True
Actual:   False

I am not sure what is wrong, but it says it expected "the predicate to return true" does this refer to whether it was deleted or not? because from tracing the code seqNr 4 is not deleted so it is correct to return "deleted:False" but perhaps this is not the issue, perhaps they don't match for another reason?

Thanks for the assistance
Noel

**Comment by alexvaluyskiy** [comment]
You can filter your replayed messages

``` csharp
var result = await ReadAsync(persistenceId, fromSequenceNumber, Math.Min(toSequenceNumber, highest), max);
result.Where(c => !c.Deleted).ForEach(recoveryCallback);
```

**Comment by nanderto** [comment]
I had 11 of 15 failing tests but the problem was the PersistenceId being empty. I had my parameters in the wrong order. That has solved all but 1 test. The WriteGuid is also blank, I can't see where that is supposed to come from so hopefully its not needed.

**Comment by nanderto** [comment]
I finally got all of the tests to pass, for journals and snapshots. Time for a little tidy up.
